### PR TITLE
Update Poetry version to 1.1.12

### PR DESCRIPTION
**Pull request by hugorodgerbrown**
Fetching from upstream repo.

### CODE REVIEW

**Review by emab — APPROVED** [review]
LGTM!

**Comment by hugorodgerbrown** [comment]
Not entirely sure what I was trying to do here - I presume just keeping up to date. Now that we have forked by introducing that change should do we still care?

**Comment by emab** [comment]
> Not entirely sure what I was trying to do here - I presume just keeping up to date. Now that we have forked by introducing that change should do we still care?

My PR doesn't include any of the upstream commits which I think are included here. If we want to stay in sync with the forked branch I do think it's worth getting some of this in here perhaps?

**Comment by hugorodgerbrown** [comment]
Closed in favour of #5

**Pull request closed without merging**
